name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: environment

permissions:
      id-token: write
      contents: read
      
jobs: 
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Setup NASM
      uses: ilammy/setup-nasm@13cbeb366c45c4379d3478cdcbadd8295feb5028

    - name: Checkout files
      uses: actions/checkout@v4

    - name: Compile NASM and run file
      run: |
        ls -al
        nasm -v
        ld -v
        nasm -f elf keyvault.asm 
        ld -m elf_i386 -s -o keyvault keyvault.o
        ls -al
        ./keyvault
        ls -al
    
    - name: Read directory again
      run: |
        ls -al

    #- name: 'Az CLI login'
    #  uses: azure/login@v2
    #  with:
    #      client-id: ${{ vars.AZURE_CLIENT_ID }}
    #      tenant-id: ${{ vars.AZURE_TENANT_ID }}
    #      subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    #- name: 'Run Azure CLI commands'
    #  run: |
    #      az account show
    #      az group list
    #      pwd
